### ISSUE TITLE
Questions about Thread Safety

### ISSUE THREAD

**Issue by symisc** [martinus/robin-hood-hashing#104]
Hi,

Does robin-hood works fine with multiple, concurrent readers threads and a single writer thread, all synchronized by `std::shared_lock` mutex?

**Comment by martinus** [comment]
Yes, this should work. All `const` operations are threadsafe can be called in parallel, but no concurrent non-const method must be called.

**Comment by symisc** [comment]
so  to resume: `table.find()` is thread safe while `table['elem'] = 'val' ` is not?

**Comment by martinus** [comment]
yes. Note that Iterators and refereces will be invalidated when you modify the table.
