### ISSUE TITLE
Insert fails with std::overflow_error

### ISSUE THREAD

**Issue by slavenf** [martinus/robin-hood-hashing#115]
Example is attached.
Example creates robin_hood::unordered_flat_set<int32_t>.
More than 5000 elements are inserted.
It fails every time.
I have used robin hood version 3.9.1

[robin-hood-fail-case.cpp.txt](https://github.com/martinus/robin-hood-hashing/files/6123498/robin-hood-fail-case.cpp.txt)

**Comment by martinus** [comment]
Thanks for the test case! Yet another case of why its bad to bake your own hash :-( I've switched the hash back to murmurhash, the version in master should work.

**Comment by martinus** [comment]
fixed with other hash
