### ISSUE TITLE
why not add robin_hood::unordered_multixxx version?

### ISSUE THREAD

**Issue by chipsethan** [martinus/robin-hood-hashing#122]
There are std::unordered_multimap and std::unordered_multiset in C++ STL. So, I hope robin_hood hash table can add the two versions as well.

**Comment by martinus** [comment]
Wow I didn't even know there is a `std::unordered_multimap`, I never needed anything like that. I'm not sure this would be worth the effort, this can be simulated with a unordered_map and a vector as the value.

**Comment by chipsethan** [comment]
If you just want to use it by yourself, your hash table does not need to adapt to anything else. But remember, it would be always a tiny "toy" in this way to be developed and maintained.
If I were you, for the 1st step, I will make it compatible to the standard hash tables in C++ STL, for the 2nd step, carrying out a thorough test with integers, strings(unicode) and many other data types, for the 3rd step, contributing code to GNU g++ with this technology of std::unordered_xxx.
I am not sure whether you can understand me or not, as English is not my native language. I mean I do not hope a sound technology would be buried in such a weird way only because it is tiny.

**Comment by martinus** [comment]
stl is bound to use the implementation that std::unordered_map uses due to compatibility issues.
