### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by Fr3DBr** [martinus/robin-hood-hashing#123]
Hey, would you recommend your unordered_map, for fast ipv4 matching ? I'm currently using std::unordered_map, however at 30~60k random IP addresses (4 byte integers) the lookup time starts to increase badly, so my question is, if your version would be recommended instead ? :)

**Comment by chipsethan** [comment]
Hash table is NOT the best data structure to handle IP addresses. I think you can compare some type of other data structures such as tries, suffix/prefix trees etc on Wikipedia.

**Comment by martinus** [comment]
I'd use something like `robin_hood::unordered_flat_set<uint32_t>` and represent the IP as an uint32_t. It should be faster, but better try the benchmark first.

**Comment by Fr3DBr** [comment]
In my tests, the fastest stl container for my case, was the std::unordered_map, however at a certain point, the lookup time increases exponentially hehe.
