### ISSUE TITLE
boost

### ISSUE THREAD

**Issue by afabri** [martinus/robin-hood-hashing#124]
Are there any plans to propose that to boost.org and/or distribute it under the boost license?

**Comment by martinus** [comment]
No, I don't have any plans regarding that. To me the library is currently in maintainence mode, I only do occasional bugfixes when necessary and accept PRs.

**Comment by afabri** [comment]
What do you mean with "in maintenance mode"?

**Comment by martinus** [comment]
I don't have any features planed
