### ISSUE TITLE
char* key support

### ISSUE THREAD

**Issue by KTRosenberg** [martinus/robin-hood-hashing#126]
I am unsure of whether I can use char* or const char* as a key. Is there documentation for how to add a custom type like the following?

```
struct CString_With_Length {
    char* data;
    size_t byte_length;
};
```

I would just like to use this for a key.

**Comment by martinus** [comment]
I'd use a `std::string_view`

**Comment by KTRosenberg** [comment]
I should’ve been more specific that I’d like to use a more complex custom type and was looking for instructions for managing the memory for that type. Also, I am hoping to remove dependencies on the std stl.

**Comment by martinus** [comment]
This is not specific to robin_hood map, please ask e.g. at https://www.reddit.com/r/cpp_questions/ or on stackoverflow
