### ISSUE TITLE
Consider adding support for conan

### ISSUE THREAD

**Issue by seertaak** [martinus/robin-hood-hashing#13]
Hi, as the title suggests, it would be awesome if this library were available via conan.

**Comment by martinus** [comment]
I'm unfortunately unfamiliar with conan. Do you have a link how to best do this?

**Comment by seertaak** [comment]
Following is an example take from [https://docs.conan.io/en/latest/howtos/makefiles.html#](here). The python code below goes in a file at the root of your project called `conanfile.py`. After that you need to run some `conan` commands... not the least to upload to `bintray` or similar. I'm pretty busy but assuming you get further (i.e. manage to make command below work) I can guide  you through or put you in touch with someone who can do this.

```
from conans import ConanFile, AutoToolsBuildEnvironment
from conans import tools

class HelloConan(ConanFile):
    name = "Hello"
    version = "0.1"
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"
    exports_sources = "src/*"

    def build(self):
        with tools.chdir("src"):
            env_build = AutoToolsBuildEnvironment(self)
            # env_build.configure() # use it to run "./configure" if using autotools
            env_build.make()

    def package(self):
        self.copy("*.h", dst="include", src="src")
        self.copy("*.lib", dst="lib", keep_path=False)
        self.copy("*.a", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["hello"]
```

**Comment by seertaak** [comment]
By the way, there's a conan channel on slack (cpplang.slack.com) and the people of there have always been very responsive and helpful. They're really trying hard to get new libraries -- I would be very surprised if they don't give you extensive hand-holding for your library :)

**Comment by jcageman** [comment]
> I'm unfortunately unfamiliar with conan. Do you have a link how to best do this?

Since its a header only library i would suspect you can easily copy an example from any other header only library.

**Comment by martinus** [comment]
It seems to me I can find good examples this way: https://github.com/search?q=conanfile.py+header-only+single-file&type=Code
