### ISSUE TITLE
Support for custom allocator ? 

### ISSUE THREAD

**Issue by jcelerier** [martinus/robin-hood-hashing#136]
Hello, 
the library seems to necessarily use std::malloc for now.

Is there a plan to have support for custom allocators at some point ? 
Thanks !

**Comment by martty** [comment]
I would be also interested in this - if it is just planned could even try to hash something out.

**Comment by martinus** [comment]
As stated in the README.md, I don't have the time to do further development on the map and will only do critical bug fixes. Sorry!
