### ISSUE TITLE
compiler warning VS2017 (version 19.00)

### ISSUE THREAD

**Issue by jcageman** [martinus/robin-hood-hashing#14]
relevant code: https://godbolt.org/z/7l35xp

```
warning C4100: 'tuple2': unreferenced formal parameter
note: see reference to function template instantiation 'robin_hood::pair<const int,T>::pair<_Ty&&,0,,>(std::tuple<_Ty &&> &,std::tuple<> &,std::integer_sequence<unsigned int,0>,std::integer_sequence<::size_t>)' being compiled
```

With 19.00 of the VS compiler i can reproduce the warning (my exact version is 19.00.24215.1 locally). With the latest VS compiler i can't reproduce it. See the result of both compiler versions in the link above. The code itself seems fine, so i suspect it might be a missing compiler feature or even a bug.

**Comment by martinus** [comment]
Thanks for reporting that, it should now be fixed in 3.0.1
