### ISSUE TITLE
compilation errors for iterators

### ISSUE THREAD

**Issue by jcageman** [martinus/robin-hood-hashing#15]
See examples in: https://godbolt.org/z/-CLsqo

**Comment by martinus** [comment]
I've left out it++ on purpose because it requires generating a temporary object, so please use ++it instead.

Default initialized iterators are not supported, but I accept pull requests :)

**Comment by jcageman** [comment]
Oke, i agree with your design choices there. I'll rewrite the code 👍 All uses i found of default initialized iterators were not really needed anyways

**Comment by martinus** [comment]
I'll see what I can do

**Comment by jcageman** [comment]
> I'll see what I can do

At work we have our own iterator implementation and this iterator needs to be a member, problem is that we have to default initialize it, so i actually would need to be able to default construct iterators.

**Comment by martinus** [comment]
I think I missread the standard, end() doesn't need to be equal to default constructed iterator.

So I have now added default constructed iterators in version 3.1.0
