### ISSUE TITLE
A problem with robin_hood::erase

### ISSUE THREAD

**Issue by gian-master** [martinus/robin-hood-hashing#154]
hello, I need some help. I have a program like this:

robin_hood::unordered_map<int*, int> kk;
int *a = new int;
int *b = new int;
int *c = new int;
kk[a] = 1;
kk[b] = 1;
kk[c] = 1;
for(auto iter= kk.begin(); iter != kk.end();) {
  if(iter->second == 1) {
    kk.erase(iter++);
  }else{
    iter++;
  }
}
cout<<"map size:"<<kk.size();
delete a;
delete b;
delete c; 

I run it ten times, and get output like this:
map size:0
map size:0
map size:0
map size:0
map size:0
map size:0
map size:1
map size:0
map size:0
map size:0

obviously, the output is not always 0， is that means the erase func is not support like this?

**Comment by martinus** [comment]
iterators are not stable, so you must not do ` kk.erase(iter++);`.

**Comment by gian-master** [comment]
Thanks very much,it looks like I've been doing it the wrong way before, I've learned a lot
