### ISSUE TITLE
terminate called after throwing an instance of 'std::overflow_error'   what():  robin_hood::map overflow Aborted (core dumped)

### ISSUE THREAD

**Issue by mayukhnec** [martinus/robin-hood-hashing#156]
I am facing  "robin_hood::map overflow"  exception  with robinhood version 3.5.1  when I run my code on Ubuntu 18.04.5 LTS environment. I even tried using robinhood 3.11.5 latest version. But still the issue is same.
![error_anyburl](https://user-images.githubusercontent.com/109209864/178713200-e244eaee-e0b3-4c6d-8e88-b099091bac5e.png)

**Comment by martinus** [comment]
Hi, can you try if it works with `ankerl::unordered_dense::map`? https://github.com/martinus/unordered_dense

**Comment by mayukhnec** [comment]
In my code I am using "robinhood::unordered_set" and "robinhood::unordered_map" . Both of these I cannot find in this ankerl. Can you help me with equivalent drop-in replacement to robinhood::unordered_set and robinhood::unordered_map or any equivalent.

**Comment by mayukhnec** [comment]
I am facing  lot of errors while compiling unordered_dense.h . Please find error file attached
[error.txt](https://github.com/martinus/robin-hood-hashing/files/9112924/error.txt)

**Comment by martinus** [comment]
unordered_dense is requires C++17 or higher

**Comment by martinus** [comment]
What issues are you facing? use the map/set's `value_type` instead of `std::pair` / `robin_hood::pair` so your code works generically.
