### ISSUE TITLE
How can I further improve performance in a read-only load?

### ISSUE THREAD

**Issue by wangqiim** [martinus/robin-hood-hashing#158]
It is a awesome hashmap implement! I have get significant performance improvement(about 2x) after replacing the std:unordered_map (read only from 50,000,000 map).
- Do you have any ideas or suggestions about how can I further improve performance in a read-only workload? 

In this case, After once write about 50,000,000 <int64, bytes[280]> and  50,000,000 <bytes[280], int>. I only focus on Read Only performance.  

Thanks.

**Comment by martinus** [comment]
what do you mean by read only, find or iterating? If iteration speed is important you should try https://github.com/martinus/unordered_dense

**Comment by wangqiim** [comment]
> what do you mean by read only, find or iterating? If iteration speed is important you should try https://github.com/martinus/unordered_dense

find
