### ISSUE TITLE
clang++ on windows

### ISSUE THREAD

**Issue by ktprime** [martinus/robin-hood-hashing#25]
././tsl/robin_hood.h:150:31: error: unknown type name 'uint128_t'
    auto result = static_cast<uint128_t>(a) * static_cast<uint128_t>(b);
                              ^
././tsl/robin_hood.h:150:59: error: unknown type name 'uint128_t'
    auto result = static_cast<uint128_t>(a) * static_cast<uint128_t>(b);

**Comment by martinus** [comment]
Thanks for reporting, I will have a look at it
