### ISSUE TITLE
What does unaligned_load do?

### ISSUE THREAD

**Issue by tuket** [martinus/robin-hood-hashing#36]
More a question than an issue (sorry I couldn't figure out how to add labels in github).

I've been reading the source code and, even though there is a comment,  I can't understand what is the purpose of this function.

```cpp
template <typename T>
inline T unaligned_load(void const* ptr) noexcept {
    // using memcpy so we don't get into unaligned load problems.
    // compiler should optimize this very well anyways.
    T t;
    memcpy(&t, ptr, sizeof(T));
    return t;
}
```

Why not just do a cast?
```cpp
*reinterpret_cast<T*>(ptr);
```

I've tried running both in my PC, and they seem to do the same, so may it's a performance thing?

Thanks for making this awesome piece of code :)

**Comment by martinus** [comment]
If you just have the `*reinterpret_cast<T*>(ptr);` and compile and run this for e.g. Solaris Sparc,  and then try to use this on data that is not 64bit aligned, e.g. like this:
```cpp
char const* str = "hello world";
uint64_t val = unaligned_load<uint64_t>(str+1);
```
Then your program will simply crash with a SIGBUS error.

**Comment by tuket** [comment]
Wow, that's very interesting. Thanks for your answer
