### ISSUE TITLE
The library is not working when compiled with -fno-exceptions

### ISSUE THREAD

**Issue by silviucpp** [martinus/robin-hood-hashing#41]
Hello,

Unfortunately for projects compiled with `-fno-exceptions` you can't use the library and need to stick with `std::` one. Any plan to support also this ?

Silviu

**Comment by martinus** [comment]
I don't really know anything about that use case. Why would a project use `-fno-exceptions`? What does the std map do when allocation fails?

**Comment by silviucpp** [comment]
Hello,

I have no idea what stl is doing. But because google is not using exceptions into their projects:
https://google.github.io/styleguide/cppguide.html#Exceptions lot of their projects are built with -fno-exceptions. STL for some reason works ok but when trying to replace std::unordered_map with your lib it's not longer compiling if not dropping -fno-exceptions

Silviu

**Comment by martinus** [comment]
Ok it seems the stl simply replaced all throws with abort() with that flag. I think this should be simple to add

**Comment by silviucpp** [comment]
Oh I see.. good to know. Anyway if you are working with google open source projects most of them are compiled with -fno-exceptions. So supporting this might be a good idea.

Silviu

**Comment by martinus** [comment]
Can you try if this latest version works for you: https://raw.githubusercontent.com/martinus/robin-hood-hashing/master/src/include/robin_hood.h

**Comment by martinus** [comment]
closing, as it works for me in my builds (even tests work)
