### ISSUE TITLE
Can't use same struct for both hashing and equality

### ISSUE THREAD

**Issue by jthemphill** [martinus/robin-hood-hashing#43]
Some programmers like to use the same struct for both hashing and equality when defining custom types. [See this block of code in HHVM](https://github.com/facebook/hhvm/blob/master/hphp/runtime/vm/jit/store-elim.cpp#L274-L287) for a real-world example.

This practice is supported by `std::unordered_map`:

```
#include <iostream>
#include <unordered_map>
#include <utility>

#include "robin_hood.h"

template<typename T, typename U, typename V, typename W>
using Map = std::unordered_map<T, U, V, W>;
// using Map = robin_hood::unordered_map<T, U, V, W>;
// doesn't compile if you use robin_hood instead

struct HashCmp {
  size_t operator()(int a) const {
    return a;
  }

  size_t operator()(int a, int b) const {
    return a == b;
  }
};

int main() {
  Map<int, int, HashCmp, HashCmp> m;
}
```

**Comment by martinus** [comment]
There is a workaround: https://github.com/martinus/robin-hood-hashing/blob/master/src/test/unit/unit_diamond.cpp

I agree though that it would be nice to support the same syntax as `std::unordered_map`. Not sure if this is possible though without introducing any more member variables.

**Comment by martinus** [comment]
I've now implemented the wrapper-class workaround in robin_hood map. Now you should be able to use `StoreKeyHashCmp` for both hash and equal without the need for any wrapper class.
