### ISSUE TITLE
Feature request: Add ability to save and load a hash_map to / from disk

### ISSUE THREAD

**Issue by WhiteRusssian** [martinus/robin-hood-hashing#47]
Firstly, let me tell you that I am very satisfied with your robin hood hash map. It performs extremely well and the the node map in particular is very memory efficient. Thank you for sharing this with us.

Since I am dealing with relatively large dynamically created hash maps of up to 15GB I would be interested in having the ability to save a hash map to disk and restore it later. Do you have a preferred / tested method to achieve this?

**Comment by martinus** [comment]
Hi, glad that it's working well for you! I have never tried to dump and load such a huge map. I'd say it is probably simplest to first write the size, and then iterate through the map and write all the key value pairs. When loading use the size to reserve() the correct size, then sequentially emplace each entry
