### ISSUE TITLE
consider supporting pmr::memory_resource?

### ISSUE THREAD

**Issue by sandsc** [martinus/robin-hood-hashing#56]

**Comment by marciso** [comment]
+1,
2 use cases came across in my usage: 
 - I eliminate `malloc`/`free` to extreme: I know how many elements will be cached, so I can pre-allocate from the stack. 
 - I have a memory pool on mmapped file (all allocators are taking space from mmapped file; with custom types, like `std::basic_string<..., my_allocator>`) it would be great if I could re-create the map from previously saved state in the file.

**Comment by martinus** [comment]
Hi, I don't get how it would be possible to use the allocator to recreate the map. It might be possible with a specialized call, but this wouldn't be part of memory_resoure as far as I understand it
