### ISSUE TITLE
Crashing with overflow_error

### ISSUE THREAD

**Issue by morispi** [martinus/robin-hood-hashing#64]
Hello,

I am currently trying to integrate robin hood hashing into my project.
As mentioned on your github, I simply included the robin_hood.h and used robin_hood::unordered_map instead of std::unordered_map.

However, upon start, my program crashes and reports the following error:

terminate called after throwing an instance of 'std::overflow_error'
  what():  robin_hood::map overflow
Command terminated by signal 6

Do you have any idea what could cause this?

Thanks!

Cheers,
Pierre

**Comment by martinus** [comment]
hi, what hash are you using?

**Comment by martinus** [comment]
robin_hood needs a good hash to work. For integral types `robin_hood::hash` is used which usually is excellent

**Comment by morispi** [comment]
Hi,

Sorry for answering so late.
I didn't modify nor specify any particular hash. How / where am I supposed to specify it?

The github guidelines only mention:
    Add robin_hood.h to your C++ project.
    Use robin_hood::unordered_map instead of std::unordered_map
    Use robin_hood::unordered_set instead of std::unordered_set

I'm a bit lost here.

Thanks,
Pierre

**Comment by jmousel** [comment]
I've seen this same issue when using a hashmap of ints. I found a successful workaround was to use the Murmur3 finalizer defined in robin_hood.h instead of the umul128 hasher.

**Comment by martinus** [comment]
I've replaced the current hash in `master` Could you try again?

**Comment by morispi** [comment]
Just checked, seems to work pretty well!
Thanks for the fix.

Cheers,
Pierre
