### ISSUE TITLE
GCC -O2 -Wstrict-aliasing=2 warnings

### ISSUE THREAD

**Issue by avbe** [martinus/robin-hood-hashing#66]
GCC reports strict aliasing issues with -O2 (or higher optimization level) and -Wstrict-aliasing=2

```
robin_hood.h:2176:47: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
robin_hood.h:2160:50: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
```

These are probably false positives, which can be treated with

`#pragma GCC diagnostic ignored "-Wstrict-aliasing"`

or using less questionable pointer types conversion.

Reproduced with gcc versions 6.3.0 and 8.3.0.

**Comment by martinus** [comment]
Thanks, fixed
