### ISSUE TITLE
emplace invalidates existing iterators

### ISSUE THREAD

**Issue by Oipo** [martinus/robin-hood-hashing#67]
As can be seen on https://godbolt.org/z/AHH2G3 there's a bug that invalidates existing iterators.

**Comment by Oipo** [comment]
Same thing happens with insert, but not with erase.

**Comment by jmousel** [comment]
robin_hood doesn't offer the same iterator stability guarantees as std::unordered_map. Insert, emplace and erase invalidate all iterators as well references and pointers to keys or data.

**Comment by Oipo** [comment]
Oh, right, thanks.
