### ISSUE TITLE
postfix increment operator

### ISSUE THREAD

**Issue by marciso** [martinus/robin-hood-hashing#68]
May I suggest the following patch:

```
diff a/robin_hood.h b/robin_hood.h
--- a/robin_hood.h
+++ b/robin_hood.h
@@ -1199,6 +1199,14 @@ private:
             return *this;
         }

+        Iter operator++(int) noexcept {
+            Iter aux = *this;
+            mInfo++;
+            mKeyVals++;
+            fastForward();
+            return aux;
+        }
+
         reference operator*() const {
             return **mKeyVals;
         }
```

To satisfy LegacyInputIterator requirement, where post- and pre-increment are possible.

**Comment by bstaletic** [comment]
This is also the reason why this library can't be used with the C++20 algorithms. The algorithms require that `robin_hood::unordered_map<K,V>::iterator` satisfies `std::input_or_output_iterator`, which requires `std::weakly_incrementable`. `std::weakly_incrementable` directly checks that it can do `it++`.

**Comment by martinus** [comment]
Thanks, added in `master`.
