### ISSUE TITLE
exposing robin_hood::hash_bytes

### ISSUE THREAD

**Issue by sfgorky** [martinus/robin-hood-hashing#69]
Hello, 
I am uing the 'hood-hashing' class with great success. However for my application, I needed to expose (as inline) the function 'hash_bytes', since the code I'm working on has its own string class - and I wanted to have use the 'hood hash' function as a string...

Would it be possible to do that on the next release ? in a way I don't need to modify the code!

thanks.

**Comment by martinus** [comment]
I don't know what you mean by expose? You can already use it with `robin_hood::hash_bytes(data, size)`.
