### ISSUE TITLE
implement robin_hood::unordered_set

### ISSUE THREAD

**Issue by martinus** [martinus/robin-hood-hashing#7]
think about how to do this without duplicating everything

**Comment by bbsnonsence** [comment]
Would love to see this, i use unordered_set alot

**Comment by dnbaker** [comment]
I would find this quite useful; for an application I'm developing, I am currently using robin_hood::unordered_flat_map for maps and ska::flat_hash_set for sets, and it would be nice to have only one dependency.

**Comment by martinus** [comment]
fixed by #58
