### ISSUE TITLE
robin_hood::hash returns different result for smart ptr and raw pointer.

### ISSUE THREAD

**Issue by feverzsj** [martinus/robin-hood-hashing#83]
auto u = std::make_unique<int>();
    assert(robin_hood::hash<decltype(u)>()(u) == robin_hood::hash<int*>()(u.get()));

since robin_hood::hash is only specialized on raw pointer and leaves unique_ptr cases to general implementation, the result is surprisingly different. This also happens to string/string_view/...

The obvious issue with this is we can't implement heterogeneous hash easily by directly using robin_hood::hash.

**Comment by martinus** [comment]
Hi, thanks for the report! I've now implemented hash for smart pointer and string views, and more generic version for strings. 

It should work with the latest version: https://github.com/martinus/robin-hood-hashing/blob/master/src/include/robin_hood.h

**Comment by martinus** [comment]
Fixed in release 3.8.0
