### ISSUE TITLE
max_load_factor compatible 

### ISSUE THREAD

**Issue by ktprime** [martinus/robin-hood-hashing#85]
changed flollows can compatible with std::unordered_map.
float max_load_factor(float lf) const noexcept { // NOLINT(modernize-use-nodiscard)
        ROBIN_HOOD_TRACE(this)
        return MaxLoadFactor100 / 100.0F;
    }

**Comment by martinus** [comment]
robin_hood map uses a template parameter, so it is not possible to set the max_load_factor at runtime. Is it an issue to not have this method? I don't want to have it here and do nothing, just to be more compatible

**Comment by ktprime** [comment]
from  benchamrk wyhash is the fastest string hash(for hash map).  https://github.com/wangyi-fudan/wyhash
your can try test and compre it with your robin_hood::hash. 
my emhash use wyhash(string key only) and  gain 20% performance improved .

**Comment by martinus** [comment]
I'm switching to using hardware accelearated CRC32 if available.
