### ISSUE TITLE
ADL + unscoped call to free = ambiguous overload

### ISSUE THREAD

**Issue by Ryan-rsm-McKenzie** [martinus/robin-hood-hashing#90]
The unscoped call to `free` [here](https://github.com/martinus/robin-hood-hashing/blob/master/src/include/robin_hood.h#L2302) can find unwanted overloads of the function and throw compilation errors. Here's an example:

```cpp
#include <cstdlib>

#include "robin_hood.h"

namespace foo
{
	void free(void* ptr) { std::free(ptr); }
	enum bar {};
}

int main()
{
	robin_hood::unordered_set<foo::bar> error;
	return 0;
}
```

Resolving the scope like `::free` should solve it.

**Comment by martinus** [comment]
Thanks for finding this, should be fixed in the latest commits (no release yet though)
