### ISSUE TITLE
Please adding functional std (Windows)

### ISSUE THREAD

**Issue by SanyaOs** [martinus/robin-hood-hashing#95]
For the compatibility of my projects, I am missing a few features compared to std-libraries. For example: insert (with pair), increment iterator  ( operator ++ )  , and other ...

**Comment by martinus** [comment]
robin_hood doesn't use std::pair, but you can easily use the map's `value_type`. Then your code is standard conform and works with both `std::unordered_map` and `robin_hood` maps.

operator++ is already there

**Comment by SanyaOs** [comment]
problem rewrite many source code (in old style :) ), i hope only change namespace in *.h  file .  operator ++ - you use prefix  form (++i) , in my source postfix form (i++). and another problem in some source have reverse_iterator

**Comment by martinus** [comment]
Won't fix, as using std::pair would be a performance problem in some cases. There are plenty of standard conform alternatives that don't require hardcoded std::pair, you might also also use e.g. emplace.
